# Site settings
title: 云叔扯淡
email: i@lixyun.com
description: > # this means to ignore newlines until "baseurl:"
 This is a blog site for a helpless mid-age Chinese DASHU. All posts are not supposed to be shared and read by anyone except himself. Anyway, have fun!
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://www.lixyun.com" # the base hostname & protocol for your site
twitter_username: leoshcn
timezone: Hongkong
permalink: /blog/:year/:title.html

paginate: 20
paginate_path: "blog/page:num/"

# Build settings
markdown: kramdown

#External service
github_url: "https://github.com/leoshcn/"
twitter_url: "https://twitter.com/leoshcn"
linkedin_url: "https://linkedin.com/in/leoshcn"
feed_url: "http://www.lixyun.com/feed.xml"
flickr_url:"https://www.flickr.com/photos/leoshcn/"

