# Site settings
title: 云叔扯淡
email: i@lixyun.com
description: > # this means to ignore newlines until "baseurl:"
 This is a blog site for a helpless mid-age Chinese DASHU. All posts are not supposed to be shared and read by anyone except himself. Anyway, have fun!
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: leoshcn
github_username:  leoshcn
timezone: Hongkong
permalink: /:year/:title.html

paginate: 10
paginate_path: "page/page:num/"

# Build settings
markdown: kramdown
